---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - execution.agentforge.dev
  resources:
  - agentruns
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - execution.agentforge.dev
  resources:
  - agentruns/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - execution.agentforge.dev
  resources:
  - agentruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
